Repository boostcampwm-2024/refactor-web36-QLAB, pull requests merged in 2025-01, with the labels that each got.

#28 [#7] MySQL, Redis 클러스터에 생성
  kubernetis/redis-deployment.yaml
  kubernetis/redis-pvc.yaml
  kubernetis/redis-service.yaml
  kubernetis/serverDB-deployment.yaml
  kubernetis/serverDB-pvc.yaml
  kubernetis/serverDB-service.yaml
Labels: INFRA

#35 [#35] 활성 사용자 수 write-back 방식으로 갱신 로직 구현
  BE/src/app.module.ts
  BE/src/config/redis/redis.service.ts
  BE/src/query/query.service.ts
  DBManager/package-lock.json
  DBManager/package.json
  DBManager/src/K8S/KubernetesService.ts
  DBManager/src/active-user/active-user.module.ts
  DBManager/src/active-user/active-user.service.ts
  DBManager/src/app.controller.ts
  DBManager/src/app.module.ts
  DBManager/src/app.service.ts
  DBManager/src/config/redis/redis.module.ts
  DBManager/src/config/redis/redis.service.ts
Labels: DB-Manager

#33 [#2] 쿠버네티스 구조 세팅
  BE/.dockerignore
  BE/src/config/query-database/admin-db-manager.service.ts
  FE/.dockerignore
  FE/conf/nginx.conf
  kubernetes/apiServer-deployment.yaml
  kubernetes/apiServer-service.yaml
  kubernetes/queryDB-deployment.yaml
  kubernetes/redis-deployment.yaml
  kubernetes/redis-pvc.yaml
  kubernetes/redis-service.yaml
  kubernetes/secret.yaml
  kubernetes/serverDB-deployment.yaml
  kubernetes/serverDB-pvc.yaml
  kubernetes/serverDB-service.yaml
  kubernetes/webServer-deployment.yaml
  kubernetes/webServer-service.yaml
  package.json
  scripts/minikube.ps1
  scripts/minikube.sh
Labels: INFRA

#34 [#26] Pod 생성 및 삭제 이벤트 발생 구독
  DBManager/package-lock.json
  DBManager/src/K8S/KubernetesService.ts
  DBManager/src/app.controller.ts
  DBManager/src/app.module.ts
  DBManager/src/config/redis/redis.service.ts
  DBManager/src/k8s/K8SApi.module.ts
  DBManager/src/k8s/K8SApi.service.ts
Labels: DB-Manager

#36 [#32] Api-server Admin connection 제거 & db-manager DB 생성 삭제 로직 구현
  BE/src/config/query-database/admin-db-manager.service.ts
  BE/src/config/query-database/query-db.moudle.ts
  BE/src/config/query-database/user-db-manager.service.ts
  BE/src/config/query-database/user-db.moudle.ts
  BE/src/config/redis/redis.module.ts
  BE/src/config/redis/redis.service.ts
  BE/src/query/query.controller.ts
  BE/src/query/query.module.ts
  BE/src/query/query.service.ts
  BE/src/record/file.service.ts
  BE/src/record/record.controller.ts
  BE/src/record/record.module.ts
  BE/src/record/record.service.ts
  BE/src/table/dto/res-table.dto.ts
  BE/src/table/table.controller.ts
  BE/src/table/table.module.ts
  BE/src/table/table.service.ts
  BE/src/usage/usage.module.ts
  BE/src/usage/usage.service.ts
  BE/test/record/record.service.spec.ts
  BE/test/session/redis.service.spec.ts
  DBManager/package-lock.json
  DBManager/package.json
  DBManager/src/active-user/active-user.service.ts
  DBManager/src/app.controller.ts
  DBManager/src/app.module.ts
  DBManager/src/config/redis/redis.service.ts
  DBManager/src/k8s/K8SApi.service.ts
  DBManager/src/session/session-event.handler.ts
  DBManager/src/session/session-event.module.ts
  DBManager/src/user-db/user-db.connector.ts
  DBManager/src/user-db/user-db.module.ts
  DBManager/src/user-db/user-db.service.ts
  FE/package-lock.json
  FE/package.json
  FE/src/types/interfaces.ts
Labels: API-Server, DB-Manager

#41 [#8] NKS세팅
  kubernetes/base/apiServer-deployment.yaml
  kubernetes/base/apiServer-service.yaml
  kubernetes/base/kustomization.yaml
  kubernetes/base/queryDB-deployment.yaml
  kubernetes/base/redis-deployment.yaml
  kubernetes/base/redis-pvc.yaml
  kubernetes/base/redis-service.yaml
  kubernetes/base/secret.yaml
  kubernetes/base/serverDB-deployment.yaml
  kubernetes/base/serverDB-pvc.yaml
  kubernetes/base/serverDB-service.yaml
  kubernetes/base/webServer-deployment.yaml
  kubernetes/base/webServer-service.yaml
  kubernetes/overlays/dev/apiServer-deployment-patch.yaml
  kubernetes/overlays/dev/apiServer-service-patch.yaml
  kubernetes/overlays/dev/kustomization.yaml
  kubernetes/overlays/dev/redis-service-patch.yaml
  kubernetes/overlays/dev/secret.yaml
  kubernetes/overlays/dev/serverDB-service-patch.yaml
  kubernetes/overlays/dev/webServer-deployment-patch.yaml
  kubernetes/overlays/prod/apiServer-deployment-patch.yaml
  kubernetes/overlays/prod/kustomization.yaml
  kubernetes/overlays/prod/queryDB-deployment-patch.yaml
  kubernetes/overlays/prod/redis-deployment-patch.yaml
  kubernetes/overlays/prod/serverDB-deployment-patch.yaml
  kubernetes/overlays/prod/webServer-deployment-patch.yaml
  scripts/minikube.ps1
  scripts/minikube.sh
Labels: INFRA

#37 [#29] 로드밸런싱 - 새로운 세션 생성시, DB 서버 배정 (활성 사용자 정보 활용)
  BE/docker-compose.backend.local.yml
  BE/src/config/redis/redis.service.ts
  BE/src/middleware/session.middleware.ts
  DBManager/src/active-user/active-user.service.ts
  DBManager/src/app.module.ts
  DBManager/src/config/redis/redis.service.ts
  DBManager/src/loadBalancer/load-balancer.module.ts
  DBManager/src/loadBalancer/load-balancer.ts
  DBManager/src/session/session-event.handler.ts
  DBManager/src/session/session-event.module.ts
  DBManager/src/user-db/user-db.module.ts
Labels: API-Server

#45 [#38] API-Server Redis connection과 service 분리 리팩토링
  BE/.dockerignore
  BE/docker-compose.backend.local.yml
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/config/redis/redis.module.ts
  BE/src/config/redis/redis.service.ts
  BE/src/config/redisProvider/custom-redis-store.ts
  BE/src/config/redisProvider/redis-provider.module.ts
  BE/src/config/redisProvider/redis.providers.ts
  BE/src/interceptors/user-db-connection.interceptor.ts
  BE/src/middleware/session.middleware.ts
  BE/src/query/query.module.ts
  BE/src/query/query.service.ts
  BE/src/record/record.module.ts
  BE/src/redis/activeUser.repository.ts
  BE/src/redis/podList.repository.ts
  BE/src/redis/redis.module.ts
  BE/src/redis/session.repository.ts
  BE/src/table/table.module.ts
  BE/src/usage/usage.module.ts
  BE/src/usage/usage.service.ts
  BE/test/interceptor/user-db-connection.interceptor.spec.ts
  BE/test/session/redis.service.spec.ts
Labels: API-Server

#49 [#46] ActiveUser 정보 관리 로직 수정
  BE/src/interceptors/user-db-connection.interceptor.ts
  BE/src/query/query.service.ts
  BE/src/redis/activeUser.repository.ts
  BE/src/redis/podList.repository.ts
  BE/src/redis/session.repository.ts
  DBManager/src/active-user/active-user.service.ts
  DBManager/src/k8s/K8SApi.service.ts
  DBManager/src/session/session-event.handler.ts
  DBManager/src/user-db/user-db.connector.ts
Labels: API-Server

#51 [#15] 유저 쿼리 실행 순차처리 구현
  BE/src/app.module.ts
  BE/src/config/redisProvider/redis.providers.ts
  BE/src/interceptor/logging.interceptor.ts
  BE/src/interceptor/serialize.interceptor.ts
  BE/src/interceptor/user-db-connection.interceptor.ts
  BE/src/query/query.controller.ts
  BE/src/query/query.service.ts
  BE/src/record/record.controller.ts
  BE/src/redis/active-user.repository.ts
  BE/src/redis/ready-queue.manager.ts
  BE/src/redis/redis.module.ts
  BE/src/shell/shell.controller.ts
  BE/src/table/table.controller.ts
  BE/src/usage/usage.controller.ts
  BE/test/interceptor/user-db-connection.interceptor.spec.ts
  BE/test/redis/ready-queue.manager.spec.ts
  BE/test/redis/session.repository.spec.ts
  DBManager/src/config/redis/redis.service.ts
Labels: API-Server

#50 [#48] DB Manager Server 쿠버네티스에 추가
  DBManager/.dockerignore
  DBManager/Dockerfile
  DBManager/ecosystem.config.js
  kubernetes/base/DBManager/account.yaml
  kubernetes/base/DBManager/deployment.yaml
  kubernetes/base/DBManager/kustomization.yaml
  kubernetes/base/DBManager/role-binding.yaml
  kubernetes/base/DBManager/role.yaml
  kubernetes/base/DBManager/service.yaml
  kubernetes/base/apiServer-deployment.yaml
  kubernetes/base/apiServer/deployment.yaml
  kubernetes/base/apiServer/kustomization.yaml
  kubernetes/base/apiServer/service.yaml
  kubernetes/base/configMap.yaml
  kubernetes/base/kustomization.yaml
  kubernetes/base/queryDB/deployment.yaml
  kubernetes/base/queryDB/kustomization.yaml
  kubernetes/base/redis/deployment.yaml
  kubernetes/base/redis/kustomization.yaml
  kubernetes/base/redis/pvc.yaml
  kubernetes/base/redis/service.yaml
  kubernetes/base/serverDB/deployment.yaml
  kubernetes/base/serverDB/kustomization.yaml
  kubernetes/base/serverDB/pvc.yaml
  kubernetes/base/serverDB/service.yaml
  kubernetes/base/webServer/deployment.yaml
  kubernetes/base/webServer/kustomization.yaml
  kubernetes/base/webServer/service.yaml
  kubernetes/overlays/dev/DBManager/deployment-patch.yaml
  kubernetes/overlays/dev/DBManager/kustomization.yaml
  kubernetes/overlays/dev/DBManager/service-patch.yaml
  kubernetes/overlays/dev/apiServer/deployment-patch.yaml
  kubernetes/overlays/dev/apiServer/kustomization.yaml
  kubernetes/overlays/dev/apiServer/service-patch.yaml
  kubernetes/overlays/dev/kustomization.yaml
  kubernetes/overlays/dev/redis/kustomization.yaml
  kubernetes/overlays/dev/redis/service-patch.yaml
  kubernetes/overlays/dev/serverDB/kustomization.yaml
  kubernetes/overlays/dev/serverDB/service-patch.yaml
  kubernetes/overlays/dev/webServer/deployment-patch.yaml
  kubernetes/overlays/dev/webServer/kustomization.yaml
  kubernetes/overlays/prod/DBManager/deployment-patch.yaml
  kubernetes/overlays/prod/DBManager/kustomization.yaml
  kubernetes/overlays/prod/apiServer/deployment-patch.yaml
  kubernetes/overlays/prod/apiServer/kustomization.yaml
  kubernetes/overlays/prod/kustomization.yaml
  kubernetes/overlays/prod/queryDB/deployment-patch.yaml
  kubernetes/overlays/prod/queryDB/kustomization.yaml
  kubernetes/overlays/prod/redis/deployment-patch.yaml
  kubernetes/overlays/prod/redis/kustomization.yaml
  kubernetes/overlays/prod/serverDB/deployment-patch.yaml
  kubernetes/overlays/prod/serverDB/kustomization.yaml
  kubernetes/overlays/prod/webServer/deployment-patch.yaml
  kubernetes/overlays/prod/webServer/kustomization.yaml
  scripts/minikube.ps1
Labels: INFRA
